### ISSUE TITLE
Build error after installing package

### ISSUE THREAD

**Issue by ToyboxZach** [axxag/react-native-apple-authentication-android#2]
I am getting the following error after installing (RN 0.63.1)

src/main/java/com/facebook/react/PackageList.java:29: error: package com.reactlibrary does not exist
import com.reactlibrary.AppleAuthenticationAndroidPackage;
                       ^
/app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:120: error: cannot find symbol
      new AppleAuthenticationAndroidPackage(),
          ^
  symbol:   class AppleAuthenticationAndroidPackage
  location: class PackageList
2 errors

I know nothing about the android build system, but the java files are not getting copied into the generated folder like the rest of the packages I use.

**Comment by schlaegerz** [comment]
I followed the new steps in the readme to install and got

```
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.axxag:sign-in-with-apple-button-android:master-SNAPSHOT.
     Required by:
         project :app > project :react-native-apple-authentication-android
```
